refactor(ci): run inside containers

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -4,9 +4,17 @@ SCRIPT_HOME="$(cd "$(dirname "$0")"; pwd)"
 SNAPI_HOME="$(cd "${SCRIPT_HOME}/.."; pwd)"
 cd "${SNAPI_HOME}"
 
+# Needed to pull private deps from main repo
+if [ -z "$GITHUB_TOKEN" ]; then
+  echo "Error: GITHUB_TOKEN is not set. Exiting..."
+  exit 1
+fi
+export GITHUB_TOKEN
+
 find . -type d -name "target" -exec rm -rf {} + || true
 
-JAVA_VERSION="21.0.1-graalce"
+tmp_dir=$(mktemp -d -t check-sbt-XXXXXXXXXX)
+cp -R . ${tmp_dir}
 
 toCamel() {
   local input=$1
@@ -29,28 +37,12 @@ toCamel() {
   echo "$camel"
 }
 camelComponent=$(toCamel "${1}")
-# Needed to pull private deps from main repo
-if [ -z "$GITHUB_TOKEN" ]; then
-  echo "Error: GITHUB_TOKEN is not set. Exiting..."
-  exit 1
-fi
-export GITHUB_TOKEN
 
-# Install SDKMAN! if not present
-if [ ! -s "$HOME/.sdkman/bin/sdkman-init.sh" ]; then
-  echo "Installing SDKMAN!..."
-  curl -s "https://get.sdkman.io" | bash || { echo "SDKMAN installation failed"; exit 1; }
-fi
-source "$HOME/.sdkman/bin/sdkman-init.sh"
-
-# Install Java through SDKMAN!
-if ! sdk list java | grep -q "$JAVA_VERSION"; then
-  echo "Installing Java version $JAVA_VERSION..."
-  yes | sdk install java "$JAVA_VERSION" || { echo "Java installation failed"; exit 1; }
-  sdk default java "$JAVA_VERSION"
-  echo "Java version $JAVA_VERSION installation complete and set as default."
-fi
-sdk use java "$JAVA_VERSION"
-
-sbt update
-sbt clean "${camelComponent}"/test
+docker run \
+  -v /var/run/docker.sock:/var/run/docker.sock \
+  -v /usr/bin/docker:/usr/bin/docker \
+  -v ${HOME}/.docker/config.json:/root/.docker/config.json \
+  -v ${tmp_dir}:/root/ \
+  -e GITHUB_TOKEN=${GITHUB_TOKEN} \
+  sbtscala/scala-sbt:graalvm-community-21.0.2_1.9.9_2.12.18 \
+  /bin/bash -c "sbt clean ${camelComponent}/test"
